<?php

namespace Database\Seeders;

use App\Models\Athlete;
use Illuminate\Database\Seeder;

class AthletesSeeder extends Seeder
{
    public function run(): void
    {
        $athletes = [
            [
                'student_id' => '123456789',
                'name' => 'Michael Jordan Jr.',
                'email' => 'mjordan@cdd.edu.ph',
                'contact_number' => '123-456-7890',
                'birthdate' => '2002-03-15',
                'department' => 'School of Information Technology',
                'course' => 'BS Computer Science',
                'year_level' => '3rd Year',
                'age' => 22,
                'enrolled_units' => 18,
                'scholarship_status' => '100%',
                'sport_team' => 'Basketball',
                'team_name' => 'Hawks',
                'gdrive_link' => 'https://drive.google.com/drive/folders/1mjordan_docs',
                'status' => 'active',
                'registered_at' => now(),
            ],
            [
                'student_id' => '234567890',
                'name' => 'Sarah Williams',
                'email' => 'swilliams@cdd.edu.ph',
                'contact_number' => '123-456-7891',
                'birthdate' => '2003-07-22',
                'department' => 'School of Computer Science',
                'course' => 'BS Computer Science',
                'year_level' => '2nd Year',
                'age' => 21,
                'enrolled_units' => 20,
                'scholarship_status' => '75%',
                'sport_team' => 'Chess',
                'team_name' => 'Masters',
                'gdrive_link' => 'https://drive.google.com/drive/folders/2swilliams_docs',
                'status' => 'active',
                'registered_at' => now(),
            ],
            [
                'student_id' => '345678901',
                'name' => 'David Chen',
                'email' => 'dchen@cdd.edu.ph',
                'contact_number' => '123-456-7892',
                'birthdate' => '2002-11-08',
                'department' => 'School of Engineering',
                'course' => 'BS Engineering',
                'year_level' => '3rd Year',
                'age' => 22,
                'enrolled_units' => 19,
                'scholarship_status' => '50%',
                'sport_team' => 'Table Tennis',
                'team_name' => 'Spinners',
                'gdrive_link' => 'https://drive.google.com/drive/folders/3dchen_docs',
                'status' => 'active',
                'registered_at' => now(),
            ],
            [
                'student_id' => '456789012',
                'name' => 'Emily Rodriguez',
                'email' => 'erodriguez@cdd.edu.ph',
                'contact_number' => '123-456-7893',
                'birthdate' => '2003-02-14',
                'department' => 'School of Business and Accountancy',
                'course' => 'BS Business Administration',
                'year_level' => '2nd Year',
                'age' => 21,
                'enrolled_units' => 18,
                'scholarship_status' => '25%',
                'sport_team' => 'Badminton',
                'team_name' => 'Smashers',
                'gdrive_link' => 'https://drive.google.com/drive/folders/4erodriguez_docs',
                'status' => 'active',
                'registered_at' => now(),
            ],
            [
                'student_id' => '567890123',
                'name' => 'James Thompson',
                'email' => 'jthompson@cdd.edu.ph',
                'contact_number' => '123-456-7894',
                'birthdate' => '2002-09-30',
                'department' => 'School of Physical Education',
                'course' => 'BS Physical Education',
                'year_level' => '3rd Year',
                'age' => 22,
                'enrolled_units' => 17,
                'scholarship_status' => '100%',
                'sport_team' => 'Basketball',
                'team_name' => 'Eagles',
                'gdrive_link' => 'https://drive.google.com/drive/folders/5jthompson_docs',
                'status' => 'inactive',
                'registered_at' => now(),
            ],
            [
                'student_id' => '678901234',
                'name' => 'Maria Santos',
                'email' => 'msantos@cdd.edu.ph',
                'contact_number' => '123-456-7895',
                'birthdate' => '2001-12-05',
                'department' => 'School of Teacher Education',
                'course' => 'BS Education',
                'year_level' => '4th Year',
                'age' => 23,
                'enrolled_units' => 15,
                'scholarship_status' => '75%',
                'sport_team' => 'Volleyball',
                'team_name' => 'Spikers',
                'gdrive_link' => 'https://drive.google.com/drive/folders/6msantos_docs',
                'status' => 'graduated',
                'registered_at' => now(),
            ],
            [
                'student_id' => '789012345',
                'name' => 'Alex Kumar',
                'email' => 'akumar@cdd.edu.ph',
                'contact_number' => '123-456-7896',
                'birthdate' => '2003-04-18',
                'department' => 'School of International Hospitality Management',
                'course' => 'BS Hospitality Management',
                'year_level' => '1st Year',
                'age' => 20,
                'enrolled_units' => 21,
                'scholarship_status' => '50%',
                'sport_team' => 'Swimming',
                'team_name' => 'Dolphins',
                'gdrive_link' => 'https://drive.google.com/drive/folders/7akumar_docs',
                'status' => 'active',
                'registered_at' => now(),
            ],
            [
                'student_id' => '890123456',
                'name' => 'Lisa Johnson',
                'email' => 'ljohnson@cdd.edu.ph',
                'contact_number' => '123-456-7897',
                'birthdate' => '2002-08-25',
                'department' => 'School of Health and Sciences',
                'course' => 'BS Nursing',
                'year_level' => '3rd Year',
                'age' => 22,
                'enrolled_units' => 22,
                'scholarship_status' => '100%',
                'sport_team' => 'Track and Field',
                'team_name' => 'Runners',
                'gdrive_link' => 'https://drive.google.com/drive/folders/8ljohnson_docs',
                'status' => 'active',
                'registered_at' => now(),
            ],
        ];

        foreach ($athletes as $athlete) {
            Athlete::updateOrCreate(
                ['student_id' => $athlete['student_id']],
                $athlete
            );
        }

        $this->command->info('Athletes seeded successfully!');
    }
}
