<?php

namespace Database\Seeders;

use App\Models\RegisteredPlayer;
use App\Models\Event;
use Illuminate\Database\Seeder;

class PlayersSeeder extends Seeder
{
    public function run(): void
    {
        // Get events to associate players with
        $events = Event::all();
        
        if ($events->isEmpty()) {
            $this->command->error('No events found. Please run EventSeeder first.');
            return;
        }

        $players = [
            [
                'event_id' => 1, // Basketball Tournament
                'student_id' => '202500001',
                'name' => 'Juan Dela Cruz',
                'email' => 'juan.delacruz@cdd.edu.ph',
                'department' => 'School of Information Technology',
                'age' => 20,
                'gdrive_link' => 'https://drive.google.com/document/d/1abc123',
                'team_name' => 'Team Alpha',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Science in Information Technology',
                'year_level' => '2nd Year',
                'contact_number' => '09123456789',
                'gpa' => 3.50,
                'enrolled_units' => 18,
                'scholarship_status' => 'Academic Scholar',
                'sport_team' => 'Basketball Varsity',
            ],
            [
                'event_id' => 1, // Basketball Tournament
                'student_id' => '202500002',
                'name' => 'Maria Santos',
                'email' => 'maria.santos@cdd.edu.ph',
                'department' => 'School of Teacher Education',
                'age' => 21,
                'gdrive_link' => 'https://drive.google.com/document/d/1def456',
                'team_name' => 'Team Alpha',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Elementary Education',
                'year_level' => '3rd Year',
                'contact_number' => '09123456790',
                'gpa' => 3.75,
                'enrolled_units' => 20,
                'scholarship_status' => 'Academic Scholar',
                'sport_team' => 'Basketball Varsity',
            ],
            [
                'event_id' => 2, // Chess Championship
                'student_id' => '202500003',
                'name' => 'Carlos Reyes',
                'email' => 'carlos.reyes@cdd.edu.ph',
                'department' => 'School of Information Technology',
                'age' => 19,
                'gdrive_link' => 'https://drive.google.com/document/d/1ghi789',
                'team_name' => 'Team Beta',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Science in Computer Science',
                'year_level' => '1st Year',
                'contact_number' => '09123456791',
                'gpa' => 3.80,
                'enrolled_units' => 21,
                'scholarship_status' => 'None',
                'sport_team' => 'Chess Club',
            ],
            [
                'event_id' => 2, // Chess Championship
                'student_id' => '202500004',
                'name' => 'Ana Martinez',
                'email' => 'ana.martinez@cdd.edu.ph',
                'department' => 'School of Humanities',
                'age' => 22,
                'gdrive_link' => 'https://drive.google.com/document/d/1jkl012',
                'team_name' => 'Team Beta',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Arts in Mathematics',
                'year_level' => '4th Year',
                'contact_number' => '09123456792',
                'gpa' => 3.90,
                'enrolled_units' => 15,
                'scholarship_status' => 'Academic Scholar',
                'sport_team' => 'Chess Club',
            ],
            [
                'event_id' => 3, // Programming Hackathon
                'student_id' => '202500005',
                'name' => 'Luis Garcia',
                'email' => 'luis.garcia@cdd.edu.ph',
                'department' => 'School of Information Technology',
                'age' => 20,
                'gdrive_link' => 'https://drive.google.com/document/d/1mno345',
                'team_name' => 'Team Gamma',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Science in Information Technology',
                'year_level' => '2nd Year',
                'contact_number' => '09123456793',
                'gpa' => 3.60,
                'enrolled_units' => 18,
                'scholarship_status' => 'None',
                'sport_team' => 'Programming Club',
            ],
            [
                'event_id' => 3, // Programming Hackathon
                'student_id' => '202500006',
                'name' => 'Sofia Rodriguez',
                'email' => 'sofia.rodriguez@cdd.edu.ph',
                'department' => 'School of Engineering',
                'age' => 21,
                'gdrive_link' => 'https://drive.google.com/document/d/1pqr678',
                'team_name' => 'Team Gamma',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Science in Computer Engineering',
                'year_level' => '3rd Year',
                'contact_number' => '09123456794',
                'gpa' => 3.70,
                'enrolled_units' => 19,
                'scholarship_status' => 'Academic Scholar',
                'sport_team' => 'Programming Club',
            ],
            [
                'event_id' => 4, // Music Festival
                'student_id' => '202500007',
                'name' => 'Miguel Lopez',
                'email' => 'miguel.lopez@cdd.edu.ph',
                'department' => 'School of Humanities',
                'age' => 19,
                'gdrive_link' => 'https://drive.google.com/document/d/1stu901',
                'team_name' => 'Team Delta',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Arts in Music',
                'year_level' => '1st Year',
                'contact_number' => '09123456795',
                'gpa' => 3.40,
                'enrolled_units' => 16,
                'scholarship_status' => 'Cultural Scholar',
                'sport_team' => 'Music Ensemble',
            ],
            [
                'event_id' => 4, // Music Festival
                'student_id' => '202500008',
                'name' => 'Isabella Fernandez',
                'email' => 'isabella.fernandez@cdd.edu.ph',
                'department' => 'School of Humanities',
                'age' => 20,
                'gdrive_link' => 'https://drive.google.com/document/d/1vwx234',
                'team_name' => 'Team Delta',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Arts in Performing Arts',
                'year_level' => '2nd Year',
                'contact_number' => '09123456796',
                'gpa' => 3.55,
                'enrolled_units' => 17,
                'scholarship_status' => 'Cultural Scholar',
                'sport_team' => 'Music Ensemble',
            ],
            [
                'event_id' => 5, // Science Exhibition
                'student_id' => '202500009',
                'name' => 'Roberto Castillo',
                'email' => 'roberto.castillo@cdd.edu.ph',
                'department' => 'School of Health and Sciences',
                'age' => 21,
                'gdrive_link' => 'https://drive.google.com/document/d/1yzab567',
                'team_name' => 'Team Epsilon',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Science in Physics',
                'year_level' => '3rd Year',
                'contact_number' => '09123456797',
                'gpa' => 3.65,
                'enrolled_units' => 18,
                'scholarship_status' => 'Academic Scholar',
                'sport_team' => 'Science Club',
            ],
            [
                'event_id' => 5, // Science Exhibition
                'student_id' => '202500010',
                'name' => 'Gabriela Reyes',
                'email' => 'gabriela.reyes@cdd.edu.ph',
                'department' => 'School of Health and Sciences',
                'age' => 20,
                'gdrive_link' => 'https://drive.google.com/document/d/2cde890',
                'team_name' => 'Team Epsilon',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Science in Chemistry',
                'year_level' => '2nd Year',
                'contact_number' => '09123456798',
                'gpa' => 3.45,
                'enrolled_units' => 19,
                'scholarship_status' => 'None',
                'sport_team' => 'Science Club',
            ],
            [
                'event_id' => 5, // Science Exhibition
                'student_id' => '202500011',
                'name' => 'Antonio Santos',
                'email' => 'antonio.santos@cdd.edu.ph',
                'department' => 'School of Health and Sciences',
                'age' => 22,
                'gdrive_link' => 'https://drive.google.com/document/d/3fgh123',
                'team_name' => 'Team Epsilon',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Science in Biology',
                'year_level' => '4th Year',
                'contact_number' => '09123456799',
                'gpa' => 3.85,
                'enrolled_units' => 15,
                'scholarship_status' => 'Academic Scholar',
                'sport_team' => 'Science Club',
            ],
            [
                'event_id' => 6, // Art Workshop
                'student_id' => '202500012',
                'name' => 'Carmen Lopez',
                'email' => 'carmen.lopez@cdd.edu.ph',
                'department' => 'School of Humanities',
                'age' => 19,
                'gdrive_link' => 'https://drive.google.com/document/d/4ijk456',
                'team_name' => 'Team Zeta',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Fine Arts',
                'year_level' => '1st Year',
                'contact_number' => '09123456800',
                'gpa' => 3.30,
                'enrolled_units' => 16,
                'scholarship_status' => 'Cultural Scholar',
                'sport_team' => 'Art Club',
            ],
            [
                'event_id' => 6, // Art Workshop
                'student_id' => '202500013',
                'name' => 'Diego Martinez',
                'email' => 'diego.martinez@cdd.edu.ph',
                'department' => 'School of Humanities',
                'age' => 20,
                'gdrive_link' => 'https://drive.google.com/document/d/5lmn789',
                'team_name' => 'Team Zeta',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Visual Arts',
                'year_level' => '2nd Year',
                'contact_number' => '09123456801',
                'gpa' => 3.50,
                'enrolled_units' => 17,
                'scholarship_status' => 'None',
                'sport_team' => 'Art Club',
            ],
            [
                'event_id' => 7, // Debate Competition
                'student_id' => '202500014',
                'name' => 'Patricia Garcia',
                'email' => 'patricia.garcia@cdd.edu.ph',
                'department' => 'School of Humanities',
                'age' => 21,
                'gdrive_link' => 'https://drive.google.com/document/d/6opq012',
                'team_name' => 'Team Theta',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Arts in Political Science',
                'year_level' => '3rd Year',
                'contact_number' => '09123456802',
                'gpa' => 3.75,
                'enrolled_units' => 18,
                'scholarship_status' => 'Academic Scholar',
                'sport_team' => 'Debate Society',
            ],
            [
                'event_id' => 7, // Debate Competition
                'student_id' => '202500015',
                'name' => 'Ricardo Fernandez',
                'email' => 'ricardo.fernandez@cdd.edu.ph',
                'department' => 'School of Humanities',
                'age' => 22,
                'gdrive_link' => 'https://drive.google.com/document/d/7rst345',
                'team_name' => 'Team Theta',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Laws',
                'year_level' => '4th Year',
                'contact_number' => '09123456803',
                'gpa' => 3.95,
                'enrolled_units' => 14,
                'scholarship_status' => 'Academic Scholar',
                'sport_team' => 'Debate Society',
            ],
            [
                'event_id' => 7, // Debate Competition
                'student_id' => '202500016',
                'name' => 'Monica Rodriguez',
                'email' => 'monica.rodriguez@cdd.edu.ph',
                'department' => 'School of Humanities',
                'age' => 20,
                'gdrive_link' => 'https://drive.google.com/document/d/8uvw678',
                'team_name' => 'Team Theta',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Arts in Philosophy',
                'year_level' => '2nd Year',
                'contact_number' => '09123456804',
                'gpa' => 3.60,
                'enrolled_units' => 18,
                'scholarship_status' => 'None',
                'sport_team' => 'Debate Society',
            ],
            [
                'event_id' => 1, // Basketball Tournament
                'student_id' => '202500017',
                'name' => 'Daniel Kim',
                'email' => 'daniel.kim@cdd.edu.ph',
                'department' => 'School of Information Technology',
                'age' => 21,
                'gdrive_link' => 'https://drive.google.com/document/d/9xyz123',
                'team_name' => 'Team Alpha',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Science in Data Science',
                'year_level' => '3rd Year',
                'contact_number' => '09123456805',
                'gpa' => 3.70,
                'enrolled_units' => 18,
                'scholarship_status' => 'Academic Scholar',
                'sport_team' => 'Data Science Club',
            ],
            [
                'event_id' => 2, // Chess Championship
                'student_id' => '202500018',
                'name' => 'Emily Chen',
                'email' => 'emily.chen@cdd.edu.ph',
                'department' => 'School of Business and Accountancy',
                'age' => 20,
                'gdrive_link' => 'https://drive.google.com/document/d/9abc456',
                'team_name' => 'Team Beta',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Arts in Economics',
                'year_level' => '2nd Year',
                'contact_number' => '09123456806',
                'gpa' => 3.55,
                'enrolled_units' => 19,
                'scholarship_status' => 'None',
                'sport_team' => 'Economics Society',
            ],
            [
                'event_id' => 3, // Programming Hackathon
                'student_id' => '202500019',
                'name' => 'Michael Rodriguez',
                'email' => 'michael.rodriguez@cdd.edu.ph',
                'department' => 'School of Engineering',
                'age' => 22,
                'gdrive_link' => 'https://drive.google.com/document/d/9def789',
                'team_name' => 'Team Gamma',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Engineering in Civil',
                'year_level' => '4th Year',
                'contact_number' => '09123456807',
                'gpa' => 3.80,
                'enrolled_units' => 15,
                'scholarship_status' => 'Academic Scholar',
                'sport_team' => 'Engineering Club',
            ],
            [
                'event_id' => 4, // Music Festival
                'student_id' => '202500020',
                'name' => 'Sarah Johnson',
                'email' => 'sarah.johnson@cdd.edu.ph',
                'department' => 'School of Health and Sciences',
                'age' => 19,
                'gdrive_link' => 'https://drive.google.com/document/d/9ghi012',
                'team_name' => 'Team Delta',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Science in Nursing',
                'year_level' => '1st Year',
                'contact_number' => '09123456808',
                'gpa' => 3.45,
                'enrolled_units' => 20,
                'scholarship_status' => 'None',
                'sport_team' => 'Nursing Association',
            ],
            [
                'event_id' => 5, // Science Exhibition
                'student_id' => '202500021',
                'name' => 'James Wilson',
                'email' => 'james.wilson@cdd.edu.ph',
                'department' => 'School of Humanities',
                'age' => 21,
                'gdrive_link' => 'https://drive.google.com/document/d/9jkl345',
                'team_name' => 'Team Epsilon',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Arts in English',
                'year_level' => '3rd Year',
                'contact_number' => '09123456809',
                'gpa' => 3.65,
                'enrolled_units' => 17,
                'scholarship_status' => 'Cultural Scholar',
                'sport_team' => 'Literary Club',
            ],
            [
                'event_id' => 6, // Art Workshop
                'student_id' => '202500022',
                'name' => 'Lisa Anderson',
                'email' => 'lisa.anderson@cdd.edu.ph',
                'department' => 'School of Health and Sciences',
                'age' => 20,
                'gdrive_link' => 'https://drive.google.com/document/d/9mno678',
                'team_name' => 'Team Zeta',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Science in Psychology',
                'year_level' => '2nd Year',
                'contact_number' => '09123456810',
                'gpa' => 3.75,
                'enrolled_units' => 18,
                'scholarship_status' => 'Academic Scholar',
                'sport_team' => 'Psychology Society',
            ],
            [
                'event_id' => 7, // Debate Competition
                'student_id' => '202500023',
                'name' => 'Robert Taylor',
                'email' => 'robert.taylor@cdd.edu.ph',
                'department' => 'School of Business and Accountancy',
                'age' => 22,
                'gdrive_link' => 'https://drive.google.com/document/d/9pqr901',
                'team_name' => 'Team Theta',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Business Administration',
                'year_level' => '4th Year',
                'contact_number' => '09123456811',
                'gpa' => 3.85,
                'enrolled_units' => 14,
                'scholarship_status' => 'Business Scholar',
                'sport_team' => 'Business Club',
            ],
            [
                'event_id' => 1, // Basketball Tournament
                'student_id' => '202500024',
                'name' => 'Amanda Martinez',
                'email' => 'amanda.martinez@cdd.edu.ph',
                'department' => 'School of Health and Sciences',
                'age' => 19,
                'gdrive_link' => 'https://drive.google.com/document/d/9stu234',
                'team_name' => 'Team Alpha',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Science in Biology',
                'year_level' => '1st Year',
                'contact_number' => '09123456812',
                'gpa' => 3.40,
                'enrolled_units' => 21,
                'scholarship_status' => 'None',
                'sport_team' => 'Biology Club',
            ],
            [
                'event_id' => 2, // Chess Championship
                'student_id' => '202500025',
                'name' => 'Kevin Brown',
                'email' => 'kevin.brown@cdd.edu.ph',
                'department' => 'School of Humanities',
                'age' => 21,
                'gdrive_link' => 'https://drive.google.com/document/d/9vwx567',
                'team_name' => 'Team Beta',
                'status' => 'active',
                'registered_at' => now()->subDays(rand(1, 30)),
                'course' => 'Bachelor of Arts in History',
                'year_level' => '3rd Year',
                'contact_number' => '09123456813',
                'gpa' => 3.60,
                'enrolled_units' => 16,
                'scholarship_status' => 'Academic Scholar',
                'sport_team' => 'History Society',
            ],
        ];

        foreach ($players as $player) {
            RegisteredPlayer::updateOrCreate(
                ['student_id' => $player['student_id']],
                $player
            );
        }

        $this->command->info('Players seeded successfully!');
    }
}
